# define variables for ALMIF

# Vendor
VENDOR_TYPE_NOKIA = 'NOKIA'
VENDOR_TYPE_ERICSSON = 'ERICSSON'

# RAT
RAT_TYPE_5G = '5G'
RAT_TYPE_LTE = 'LTE'

# ALARM_STATE for DB
DB_ALARM_STATE_OCCURRED = 'O'
DB_ALARM_STATE_CLEARED = 'C'

# Equipment Type
EQUIPMENT_DU_TYPE = 'DU'
EQUIPMENT_RU_TYPE = 'RU'