# define variables for ALMIF
MY_PROC_NAME = 'ALMIF'
MY_LOG_FILE_NAME ='almif_log'

# Vendor
VENDOR_TYPE_NOKIA = 'Nokia'
VENDOR_TYPE_ERICSSON = 'Ericsson'

# RAT
RAT_TYPE_5G = '5G'
RAT_TYPE_LTE = 'LTE'

# ALARM_STATE for DB
DB_ALARM_STATE_OCCURRED = 'O'
DB_ALARM_STATE_CLEARED = 'C'

# Equipment Type
EQUIPMENT_DU_TYPE = 'DU'
EQUIPMENT_RU_TYPE = 'RU'
EQUIPMENT_ETC_TYPE = 'ETC'

# ALARM_CATEGORY
ALARM_CATEGORY_DEFAULT = 'DEFAULT'

# CONFIG LOG_LEVEL
CONFIG_LOG_LEVEL_CRITICAL = 1
CONFIG_LOG_LEVEL_ERROR = 2
CONFIG_LOG_LEVEL_WARNING = 3
CONFIG_LOG_LEVEL_INFO = 4
CONFIG_LOG_LEVEL_DEBUG = 5

