# define variables for ALMIF
MY_PROC_NAME = 'ALMIF'

# Vendor
VENDOR_TYPE_NOKIA = 'Nokia'
VENDOR_TYPE_ERICSSON = 'Ericsson'

# RAT
RAT_TYPE_5G = '5G'
RAT_TYPE_LTE = 'LTE'

# ALARM_STATE for DB
DB_ALARM_STATE_OCCURRED = 'O'
DB_ALARM_STATE_CLEARED = 'C'

# Equipment Type
EQUIPMENT_DU_TYPE = 'DU'
EQUIPMENT_RU_TYPE = 'RU'
EQUIPMENT_ETC_TYPE = 'ETC'

# ALARM_CATEGORY
ALARM_CATEGORY_DEFAULT = 'DEFAULT'